[paths]
csv_path = ""
build_directory = ""

[variables]
intensity = "sc_current"
features = ["participant", "sc_laterality"]
response = ["Biceps", "Triceps", "APB", "ADM"]

[mcmc]
num_chains = 4
num_warmup = 4000
num_samples = 4000
thinning = 4

[misc]
base = 1
