[paths]
csv_path = ""
build_directory = ""

[variables]
intensity = "sc_current"
features = ["participant", "sc_laterality"]
response = ["ADM", "APB", "Triceps"]

[mcmc]
num_chains = 4
num_warmup = 5000
num_samples = 1000
thinning = 1

[misc]
base = 1
