[paths]
csv_path = ""
build_directory = ""

[variables]
intensity = "sc_current"
features = ["participant", "sc_laterality"]
response = ["Biceps", "Triceps", "APB", "ADM"]

[mcmc]
num_chains = 4
num_warmup = 2000
num_samples = 2000
thinning = 2

[misc]
base = 1
