[paths]
csv = "/home/vishu/data/hbmep-processed/J_RCML_000/ground/1_2/data.csv"
build_dir = "/home/vishu/repos/hbmep-paper/reports/J_RCML_000/ground/1_2/"

[vars]
subject = "participant"
features = ["compound_position"]
intensity = "pulse_amplitude"
response = ["auc_1", "auc_2"]

[mcmc]
chains = 4
warmup = 4000
samples = 6000

[model]
link = "notebook"

[notebook]

[aesthetics]
base = 20

[optional-mep-data]
mep_matrix_path = "/home/vishu/data/hbmep-processed/J_RCML_000/ground/1_2/mat.npy"    # In .npy format with shape: (No. of rows in csv) x (time) x (No. of responses)
mep_time_range = [-0.01, 0.025]

[optional-mep-size-window]
mep_size_time_range = [0.0015, 0.01]