[paths]
csv = "/home/vishu/data/mock/mock.csv"
build_dir = "/home/vishu/repos/hbmep-paper/reports/laplace/J_RCML_000/ground"

[vars]
subject = "participant"
features = ["compound_position"]
intensity = "pulse_amplitude"
response = ["auc_1", "auc_3"]

[mcmc]
chains = 4
warmup = 4000
samples = 6000

[model]
link = "laplace"

[laplace]

[aesthetics]
base = 20
