[paths]
csv_path = ""
build_directory = ""

[variables]
intensity = "sc_current"
features = [["participant", "sc_laterality"]]
response = ["ADM", "APB", "Biceps", "Triceps"]

[mcmc]
num_chains = 4
num_warmup = 6000
num_samples = 2000
thinning = 1

[misc]
base = 1
