[paths]
csv_path = ""
build_directory = ""

[variables]
intensity = "pulse_amplitude"
features = [["participant", "compound_position"]]
response = ['LADM', 'LBiceps', 'LDeltoid', 'LECR', 'LFCR', 'LTriceps']

[mcmc]
num_chains = 4
num_warmup = 6000
num_samples = 2000
thinning = 1

[optional-mep-data]
# This is a .npy file with shape: (No. of rows in csv) x (time) x (No. of responses)
mep_matrix_path = "/home/vishu/data/hbmep-processed/J_RCML_000/mat.npy"
# Order of response in MEP matrix
mep_response = ['LADM', 'LBiceps', 'LBicepsFemoris', 'LDeltoid', 'LECR', 'LFCR', 'LTriceps', 'RBiceps']
mep_window = [-0.01, 0.025]
mep_size_window = [0.0015, 0.01]

[misc]
base = 20
