[paths]
csv_path = ""
build_directory = ""

[variables]
intensity = "TMSInt"
features = [["participant", "participant_condition"]]
response = ['PKPK_ADM', 'PKPK_APB', 'PKPK_Biceps', 'PKPK_ECR', 'PKPK_FCR', 'PKPK_Triceps']

[mcmc]
num_chains = 4
num_warmup = 6000
num_samples = 2000
thinning = 1

[misc]
base = 10
