[paths]
csv = ""
build_dir = "/home/vishu/repos/hbmep-paper/reports/paper/tms/injury-threshold-comparison/fcr"

[vars]
subject = "participant"
features = ["participant_condition"]
intensity = "TMSInt"
response = ['PKPK_FCR']

[mcmc]
chains = 4
warmup = 5000
samples = 1000

[model]
link = "fixed"

[fixed]

[aesthetics]
base = 10
