[paths]
csv = "/home/vishu/data/hbmep-processed/intraoperative/data.csv"
build_dir = "/home/vishu/repos/hbmep-paper/reports/human/intraoperative"

[vars]
subject = "participant"
features = ["sc_laterality"]
intensity = "sc_current"
response = ["Triceps"]

[mcmc]
chains = 4
warmup = 500
samples = 1000

[model]
link = "fixed"

[fixed]

[aesthetics]
base = 1
