[paths]
csv = "/home/vishu/data/hbmep-processed/J_SHAP/data.csv"
build_dir = "/home/vishu/repos/hbmep-paper/reports/J_SHAP/ecr"

[vars]
subject = "participant"
features = ["compound_position", "compound_charge_params"]
intensity = "pulse_amplitude"
response = ["auc_5"]

[mcmc]
chains = 4
warmup = 10000
samples = 6000

[model]
link = "fixed"

[fixed]

[aesthetics]
base = 20
