[paths]
csv = "/home/vishu/data/hbmep-processed/L_CIRC/data.csv"
build_dir = "/home/vishu/repos/hbmep-paper/reports/L_CIRC/triceps"

[vars]
subject = "participant"
features = ["compound_position"]
intensity = "pulse_amplitude"
response = ["auc_7"]

[mcmc]
chains = 4
warmup = 4000
samples = 6000

[model]
link = "fixed"

[fixed]

[aesthetics]
base = 20
