[paths]
csv = ""
build_dir = "/home/vishu/repos/hbmep-paper/reports/paper/rats/SHIE/Logistic5"

[vars]
subject = "participant"
features = ["compound_position", "compound_charge_params"]
intensity = "pulse_amplitude"
response = ["LADM", "LBiceps", "LDeltoid", "LECR", "LFCR", "LTriceps"]

[mcmc]
chains = 4
warmup = 1000
samples = 1000

[model]
link = "fixed"

[fixed]

[aesthetics]
base = 20
