[paths]
csv = "/home/vishu/data/hbmep-processed/L_SHIE/data.csv"
build_dir = "/home/vishu/repos/hbmep-paper/reports/L_SHIE/biceps"

[vars]
subject = "participant"
features = ["compound_position", "compound_charge_params"]
intensity = "pulse_amplitude"
response = ["auc_2"]

[mcmc]
chains = 4
warmup = 4000
samples = 6000

[model]
link = "fixed"

[fixed]

[aesthetics]
base = 20
