[paths]
csv = "/home/vishu/data/hbmep-processed/L_SHIE_000/data.csv"
build_dir = "/home/vishu/repos/reports/paper/J_RCML_000/run01"

[vars]
subject = "participant"
features = ["compound_position", "compound_charge_params"]
intensity = "pulse_amplitude"
response = ["auc_2"]

[mcmc]
chains = 4
warmup = 4000
samples = 6000

[model]
link = "fixed"

[fixed]

[aesthetics]
base = 20
