[paths]
csv = "simulation"
build_dir = "/home/vishu/repos/hbmep-paper/reports/simulation/"

[vars]
subject = "participant"
features = ["compound_position"]
intensity = "pulse_amplitude"
response = ["Biceps", "Triceps", "APB"]

[mcmc]
chains = 4
warmup = 4000
samples = 6000

[model]
link = "fixed"

[fixed]

[aesthetics]
base = 20
