[paths]
csv = "/home/vishu/data/hbmep-processed/J_RCML_000/ground/data.csv"
build_dir = "/home/vishu/repos/hbmep-paper/reports/tmux/J_RCML_000/ground/"

[vars]
subject = "participant"
features = ["compound_position"]
intensity = "pulse_amplitude"
response = ["auc_1"]

[mcmc]
chains = 4
warmup = 4000
samples = 6000

[model]
link = "rectified_logistic_studentT"

[rectified_logistic_studentT]

[aesthetics]
base = 20
