[paths]
csv = "/home/vishu/data/hbmep-processed/J_RCML_000/data.csv"
build_dir = "/home/vishu/repos/hbmep-paper/reports/tmux/J_RCML_000/student_T_inv/"

[vars]
subject = "participant"
features = ["compound_position"]
intensity = "pulse_amplitude"
response = ["auc_1", "auc_2", "auc_3"]

[mcmc]
chains = 4
warmup = 4000
samples = 6000

[model]
link = "rectified_logistic_studentT_inv"

[rectified_logistic_studentT_inv]

[aesthetics]
base = 20
