[paths]
csv_path = ""
build_directory = ""

[variables]
intensity = "TMSInt"
features = ["participant", "participant_condition"]
response = ['PKPK_APB', 'PKPK_ADM', 'PKPK_ECR', 'PKPK_FCR']

[mcmc]
num_chains = 4
num_warmup = 4000
num_samples = 4000
thinning = 4

[optional-mep-data]
# This is a .npy file with shape: (No. of rows in csv) x (time) x (No. of responses)
mep_matrix_path = "/home/vishu/data/hbmep-processed/human/tms/proc_2024-06-08.npy"
# Order of response in MEP matrix
mep_response = ['PKPK_ADM', 'PKPK_APB', 'PKPK_Biceps', 'PKPK_ECR', 'PKPK_FCR', 'PKPK_Triceps']
mep_window = [-0.25, 0.25]
mep_size_window = [0.0065, 0.09]

[misc]
base = 10
