[paths]
csv = ""
build_dir = "/home/vishu/repos/hbmep-paper/reports/paper/rats/J_RCML_000/model-comparison"

[vars]
subject = "participant"
features = ["compound_position"]
intensity = "pulse_amplitude"
response = ["LBiceps"]

[mcmc]
chains = 4
warmup = 5000
samples = 1000

[model]
link = "fixed"

[fixed]

[aesthetics]
base = 20
