[paths]
csv = ""
build_dir = "/home/vishu/repos/hbmep-paper/reports/HUMAN/biceps"

[vars]
subject = "participant"
features = ["sc_level", "sc_laterality"]
intensity = "sc_"
response = ["auc_2"]

[mcmc]
chains = 4
warmup = 4000
samples = 6000

[model]
link = "fixed"

[fixed]

[aesthetics]
base = 20
