[paths]
csv_path = ""
build_directory = ""

[variables]
intensity = "pulse_amplitude"
features = [["participant", "compound_position"]]
response = ["ADM", "APB"]

[mcmc]
num_chains = 4
num_warmup = 5000
num_samples = 1000
thinning = 1

[optional-mep-data]
# This is a .npy file with shape: (No. of rows in csv) x (time) x (No. of responses)
mep_matrix_path = "/home/vishu/data/hbmep-processed/introduction-data/mat.npy"
# Order of response in MEP matrix
mep_response = ["ADM", "APB"]
mep_window = [-0.01, 0.025]
mep_size_window = [0.0015, 0.01]

[misc]
base = 10
